local telescope = require("telescope")
local builtin = require("telescope.builtin")

vim.keymap.set("n", "<leader>pf", builtin.find_files, {})
vim.keymap.set("n", "<leader>pg", builtin.git_files, {})
vim.keymap.set("n", "<leader>ph", builtin.search_history, {})
vim.keymap.set("n", "<leader>pz", function()
	builtin.live_grep({ file_ignore_patterns = { "package-lock.json", "package.json", "node_modules", ".git" } })
end, {})
vim.keymap.set("n", "<leader>pr", telescope.extensions.frecency.frecency, {})
