local builtin = require("telescope.builtin")
vim.keymap.set("n", "<leader>pf", builtin.find_files, {})
vim.keymap.set("n", "<leader>pg", builtin.git_files, {})
-- vim.keymap.set('n', '<leader>pz', function()
--   builtin.grep_string({search = vim.fn.input("Grep > ")})
-- end)
--[[ vim.keymap.set('n', '<leader>pz', builtin.live_grep, {}) ]]
vim.keymap.set("n", "<leader>pz", function()
	builtin.live_grep({ file_ignore_patterns = { "package-lock.json", "package.json", "node_modules", ".git" } })
end, {})
